name: speda
description: Speda - Personal Executive Assistant

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  
  # HTTP & API
  http: ^1.1.2
  url_launcher: ^6.2.2
  file_picker: ^6.1.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Date/Time
  intl: ^0.18.1
  
  # UI Components
  cupertino_icons: ^1.0.6
  
  # Utilities
  equatable: ^2.0.5
  
  # Markdown Support
  flutter_markdown: ^0.6.23

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: FSIndustrieCd
      fonts:
        - asset: assets/fonts/FS Industrie Cd Thin.otf
          weight: 100
        - asset: assets/fonts/FS Industrie Cd Thin Italic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/FS Industrie Cd Light.otf
          weight: 300
        - asset: assets/fonts/FS Industrie Cd Light Italic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/FS Industrie Cd Regular.otf
          weight: 400
        - asset: assets/fonts/FS Industrie Cd Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/FS Industrie Cd Medium.otf
          weight: 500
        - asset: assets/fonts/FS Industrie Cd Medium Italic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/FS Industrie Cd Book.otf
          weight: 600
        - asset: assets/fonts/FS Industrie Cd Book Italic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/FS Industrie Cd Bold.otf
          weight: 700
        - asset: assets/fonts/FS Industrie Cd Bold Italic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/FS Industrie Cd Black.otf
          weight: 900
        - asset: assets/fonts/FS Industrie Cd Black Italic.otf
          weight: 900
          style: italic
