name: speda
description: Speda - Personal Executive Assistant

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  
  # HTTP & API
  http: ^1.1.2
  url_launcher: ^6.2.2
  file_picker: ^10.0.0
  google_sign_in: ^6.2.1
  
  # Local Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Date/Time
  intl: ^0.18.1
  
  # UI Components
  cupertino_icons: ^1.0.6
  
  # Utilities
  equatable: ^2.0.5
  
  # Markdown Support
  flutter_markdown: ^0.6.23
  
  # Voice Mode
  speech_to_text: ^7.0.0
  just_audio: ^0.9.40
  flutter_tts: ^4.2.0
  permission_handler: ^11.3.1
  flutter_animate: ^4.5.0
  audio_waveforms: ^1.2.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  ios: false
  windows:
    generate: true
    icon_path: "assets/icons/app_icon.png"
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#1a1a2e"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: FSIndustrieCd
      fonts:
        - asset: assets/fonts/FS Industrie Cd Thin.otf
          weight: 100
        - asset: assets/fonts/FS Industrie Cd Thin Italic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/FS Industrie Cd Light.otf
          weight: 300
        - asset: assets/fonts/FS Industrie Cd Light Italic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/FS Industrie Cd Regular.otf
          weight: 400
        - asset: assets/fonts/FS Industrie Cd Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/FS Industrie Cd Medium.otf
          weight: 500
        - asset: assets/fonts/FS Industrie Cd Medium Italic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/FS Industrie Cd Book.otf
          weight: 600
        - asset: assets/fonts/FS Industrie Cd Book Italic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/FS Industrie Cd Bold.otf
          weight: 700
        - asset: assets/fonts/FS Industrie Cd Bold Italic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/FS Industrie Cd Black.otf
          weight: 900
        - asset: assets/fonts/FS Industrie Cd Black Italic.otf
          weight: 900
          style: italic
